dist: bionic

language: go

go:
    - oldstable
    - stable
    # - tip

notifications:
    email: false

install:
    - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
    - go install github.com/mattn/goveralls@latest
  
script:
    - golangci-lint run
    - go test -v -race -covermode atomic -coverprofile=profile.cov ./...
    - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci
